# Generated by Django 2.2.5 on 2022-01-19 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20220119_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='location',
            field=models.IntegerField(default=0),
        ),
    ]
