# Generated by Django 2.2.5 on 2022-01-19 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_review_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='location',
            field=models.IntegerField(),
        ),
    ]
